// squealer-app/src/components/GeoMap.jsx
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";

function GeoMap({ geolocation }) {
  return (
    <MapContainer
      className="rounded-lg z-0"
      center={[geolocation.lat, geolocation.lon]}
      zoom={13}
      scrollWheelZoom={false}
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <Marker position={[geolocation.lat, geolocation.lon]}>
        <Popup>
          A pretty CSS3 popup. <br /> Easily customizable.
        </Popup>
      </Marker>
    </MapContainer>
  );
}

export default GeoMap;

// manager-dash/src/components/GeoMap.vue
<template>
  <p>{{ lat }} {{ lon }}</p>
  <div style="height: 100%; width: 100%">
    <l-map ref="map" v-model:zoom="zoom" :center="[lat, lon]">
      <l-tile-layer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        layer-type="base"
        name="OpenStreetMap"
      ></l-tile-layer>
      <l-marker :lat-lng="[lat, lon]" draggable> </l-marker>
    </l-map>
  </div>
</template>

<script>
import "leaflet/dist/leaflet.css";
import { LMap, LTileLayer, LMarker } from "@vue-leaflet/vue-leaflet";

export default {
  props: {
    lat: Number,
    lon: Number,
  },
  components: {
    LMap,
    LTileLayer,
    LMarker,
  },
  data() {
    return {
      zoom: 13,
    };
  },
};
</script>
